site_name: Documentação Achei-Unb


nav:
  - Home: index.md
  - Como contribuir?: documentacao-padroes-commits-branches.md 
  - Sprints:
    - Sprint 0: sprints/sprint-0.md
    - Sprint 1: sprints/sprint-1.md
    - Sprint 2: sprints/sprint-2.md
    - Sprint 3: sprints/sprint-3.md
    - Sprint 4: sprints/sprint-4.md
    - Sprint 5: sprints/sprint-5.md
    
  - Arquitetura: Architecture.md
  - Front-End: 
    - Figma: front-end/figma.md
    - Identidade Visual: front-end/Visual-identity.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    