services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=acheiunb
      - POSTGRES_USER=seu_usuario
      - POSTGRES_PASSWORD=sua_senha
      - DB_HOST=db
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: acheiunb
      POSTGRES_USER: seu_usuario
      POSTGRES_PASSWORD: sua_senha
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
