name: Tests CI

on:
  push:
    branches: 
      - main
      - 193/refactor/aumentar-a-cobertura-dos-testes-unitários
  pull_request:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          docker-compose -f API/docker-compose.yml up -d --build
          docker-compose run web python manage.py migrate
          
      - name: Run tests
        run: |
          docker-compose run web coverage run -m pytest
          docker-compose run web coverage report -m

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}