name: Tests CI

on:
  push:
    branches: 
      - main
      - 193/refactor/aumentar-a-cobertura-dos-testes-unit치rios
  pull_request:
    branches: 
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:15
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      PYTHONPATH: ${{ github.workspace }}/API  # Caminho para o diret칩rio API
      DJANGO_SETTINGS_MODULE: AcheiUnB.settings  # Ajustado para o m칩dulo correto
      DB_HOST: localhost
      DB_PORT: 5432
      DB_NAME: ${{ secrets.POSTGRES_DB }}
      DB_USER: ${{ secrets.POSTGRES_USER }}
      DB_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
      CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
      CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r API/requirements.txt

      - name: Run migrations
        working-directory: ./API  # Execute no diret칩rio API
        run: |
          python manage.py migrate --noinput

      - name: Run tests
        run: |
          pytest API/AcheiUnB/tests/ --cov=AcheiUnB --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}