name: Django CI

on:
  push:
    branches:
      - main
      - 154-taskautomação-pipeline-ci-com-testes
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        ports:
          - 5432:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ./API

      - name: Run linter
        run: black .
        working-directory: ./API

      - name: Run unit tests
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/testdb
        run: python manage.py test
        working-directory: ./API
